### ISSUE TITLE
Wiki inaccuracies

### ISSUE THREAD

**Issue by freshlycutgrass** [geteso/eso#16]
First off, in the ubuntu versions, only 16.04 is marked as LTS, when all of the listed versions actually are LTS releases. Second, CentOS being not tested is completely pointless, unless you mean it doesn't work, but in that case there should be another columm. Third, "Raspbian" is not a debian version, it's not the official name of the os, and you didn't list what raspberry pi os version it was. 
You should also include [this tutorial](https://geteso.org/6842/?start=0#p94733) on how to install it on a raspberry pi. I'd also like to note that I've followed this user's steps on a raspberry pi 4, with Raspberry Pi OS 10 installed. The author also notes that he is using Twister OS, which is also based on Raspberry Pi OS 10.

**Comment by aokod** [comment]
I've opened up the wiki to every user (I hope - I have disabled the push access restriction in the wiki which should let anybody contribute) and you are free to contribute.
CentOS just hasn't been used by any forum administrator to the best of my knowledge and I haven't had a need for a Cent environment.  I see no reason for it not to work.

I found conflicting sources on the Raspbian distro which is why I didn't update that part - some were referring to what I once thought was Raspbian as "Raspberry Pi OS" and others stated that "Raspbian" was under active development. I went with the shorter one because, well... y'know, column width.

Thank you for linking to me your conversation. I will include it!
