### ISSUE TITLE
Multibyte encoding fix for esotalk

### ISSUE THREAD

**Issue by andromeda-Z** [geteso/eso#30]
https://github.com/geteso/eso/pull/29

**Comment by aokod** [comment]
In each case, I fail to understand how adding multibyte functionality either fixes a known issue or makes the function more robust.  The only instance in which I can see this being appropriate is #29, but since the reserved words list is not expected to contain multi byte characters, this shouldn't be a problem to begin with.

I recommend that you read up on the use case of the multi byte equivalents of these functions so as to better understand whether they are appropriate in this context.  If I fail to understand the purpose of your commit, do not hesitate to correct me.
